### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ethers** [rainbeam/solidity-btc-parser#9]
Could you please include a License file?  Thanks

**Comment by rainbreak** [comment]
Sure, traveling today though. Do you have specific requirements? Would AGPL be usable?

**Comment by ethers** [comment]
I think Apache would be preferable for community.  (I'm planning to switch btcrelay to Apache from MIT)

**Comment by ethers** [comment]
Hi, it's your code so up to you which license you want, but when I mention this project to other people, they probably also want to know what the license is ;)  Thanks

**Comment by rainbreak** [comment]
@ethers: Apache v2 as of #18.

**Comment by ethers** [comment]
Thanks @rainbeam !
